### ISSUE TITLE
No route found for js/css/images

### ISSUE THREAD

**Issue by TimoVerbrugghe** [sergiotapia/magnetissimo#14]
Hi Sergio!

I followed the Debian 7 guide and installed magnetissimo on my Ubuntu 16.04 machine. Runs great, but the Web UI is not showing up correctly, since css/js & images cannot be found by the router. Node.js is installed on my machine & npm install completed successfully... something else I need to do?

**Comment by sergiotapia** [comment]
Oh man, unfortunately the Debian 7 guide was written by someone else (check the first lines in that Wiki page). I can't really recommend possible fixes because I have never used Debian.

Can you try `npm install --save-dev` or something like that maybe?

**Comment by sergiotapia** [comment]
Also, if you can please post any Chrome console output you see that would be helpful.

**Comment by TimoVerbrugghe** [comment]
Thanks for your quick reply! Did npm install --save-dev but didn't work. You can find the chrome console & router.ex output below!

npm output is:
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`

![screenshot 2016-09-01 at 22 57 55](https://cloud.githubusercontent.com/assets/7707120/18184086/a1f0a226-7097-11e6-9e7f-f7bc0dc41ab6.png)
![screenshot 2016-09-01 at 22 57 35](https://cloud.githubusercontent.com/assets/7707120/18184085/a1efc7a2-7097-11e6-9284-2278547b4572.png)

**Comment by sergiotapia** [comment]
So it looks like the culprit is: 

`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`

Based on this issue, it seems that fsevents is used by node to sniff out filesystem events and execute asset compilation. fsevents doesn't work on non-mac operating systems. I'm sorry I can't help you out sooner I'll be able to take a look on Sunday, but in the meantime this may point you in the right direction. PS: I hate npm and node. 😆 

https://github.com/nodejs/node/issues/7858

**Comment by sergiotapia** [comment]
@TimoVerbrugghe Seems like it was caused by someone unplishing an npm package by accident.

https://www.reddit.com/r/javascript/comments/50qskd/fs_npm_package_unpublished_by_mistake_and/

It has since been republished, try it again it should work.

**Comment by TimoVerbrugghe** [comment]
Mmm... Did npm install (and npm install --save-dev) again but no dice...

Also, do you know how much torrents the standard sources have in their repositories? Or any way that we can date limit the scraping? I let magnetissimo run overnight and I'm now already up to around 1,5 million torrents. (doesn't take a lot of space on my hdd though, well done :D)

**Comment by sergiotapia** [comment]
I don't really know how many torrents are inside each source. 

As to limiting the fetch rate, try setting a smaller queue size where appropriate: 

https://github.com/sergiotapia/magnetissimo/blob/master/config/config.exs#L33

Hope this helps!

**Comment by sergiotapia** [comment]
I think the issues has been solved here, it was that temporarily unpublished node package.

**Comment by TimoVerbrugghe** [comment]
Mmm... sorry to disappoint, but still won't work. Reinstalled completely, did npm install that succeeded. But when going to localhost:4000, broken ui. When I start up magnetissimo, it gives me a warning about wrong bindings for ubuntu 16.04 for node-sass, prompting me to run the command "npm rebuild node-sass". Output of that command in screenshot below.

<img width="599" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/7707120/18454372/23a06720-7944-11e6-822a-948b95a6860a.PNG">

**Comment by ndragon798** [comment]
currently having the same problem except instead of getting a messed up webui it just directs me to the landing page.

**Comment by ndragon798** [comment]
Doing some research on this and if you are on linux you should be using inotify instead of fsevents. The reasoning behind this is that inotify is for linux and fsevents is for mac.

**Comment by sergiotapia** [comment]
This should not longer be an issue with the rewrite. :)
